#!/bin/bash
set -e

echo ''
echo '.____          ___.                        __                       '
echo '|    |   _____ \_ |__   ________________ _/  |_  ___________ ___.__.'
echo '|    |   \__  \ | __ \ /  _ \_  __ \__  \\   __\/  _ \_  __ <   |  |'
echo '|    |___ / __ \| \_\ (  <_> )  | \// __ \|  | (  <_> )  | \/\___  |'
echo '|_______ (____  /___  /\____/|__|  (____  /__|  \____/|__|   / ____|'
echo '        \/    \/    \/                  \/                   \/     '
echo ''

echo "[MumukiDevstart::Laboratory] Installing dependencies...."
bundle install --quiet

echo "[MumukiDevstart::Laboratory] Running migrations (if any)...."
bundle exec rake db:migrate

echo "[MumukiDevstart::Laboratory] Starting server...."
MUMUKI_DEV_IP=${1:-localhost}
MUMUKI_PLATFORM_DOMAIN=$MUMUKI_DEV_IP:3000 \
MUMUKI_ORGANIZATION_MAPPING=path \
MUMUKI_COOKIES_DOMAIN=$MUMUKI_DEV_IP \
SECRET_KEY_BASE=aReallyStrongKeyForDevelopment \
  bundle exec rails s -p 3000 -b $MUMUKI_DEV_IP
