source 'https://rubygems.org'

ruby '~> 2.3'

gemspec

group :development do
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-remote'
  gem 'pry-byebug' unless Gem.win_platform?
  gem 'pry-stack_explorer'
  gem 'binding_of_caller'
end

gem 'codeclimate-test-reporter', :group => :test, :require => nil
