source 'https://rubygems.org'

ruby '~> 2.3'

gemspec

group :development do
  gem 'pry', '~> 0.10'
  gem 'pry-rails', '~> 0.3'
  gem 'pry-remote'
  gem 'pry-byebug', '~> 3.4' unless Gem.win_platform?
  gem 'pry-stack_explorer'
  gem 'binding_of_caller'
end

gem 'codeclimate-test-reporter', :group => :test, :require => nil
