require_relative './exceptions/forbidden_error'
require_relative './exceptions/gone_error'
require_relative './exceptions/not_found_error'
require_relative './exceptions/unauthorized_error'
require_relative './exceptions/blocked_forum_error'
