#!/bin/bash

echo "[Escualo::Atheneum] Checking DB exists..."
rake db:version > /dev/null 2>&1

if [  $? -eq 0 ]; then
  echo "[Escualo::Atheneum] DB Already exists"
else
  echo "[Escualo::Atheneum] Creating DB..."
  rake db:create db:schema:load db:seed
fi
